alias ff='git flow feature finish'
alias fs='git flow feature start'
alias gd='git diff-index --quiet HEAD -- || clear; git --no-pager diff --patch-with-stat'
alias gf='git fetch'
alias gh='git clone --recursive'
alias gs='git status --short --branch'
alias gsu='git summary'
alias gt='git stash'
